api/urls.py
# -*- coding: utf-8 -*-
# URLS DA API - UNB ALERTA - REST FRAMEWORK
from django.conf.urls import url

from .views import (
    # CATEGORIA
    CategoriaCreateAPIView,
    CategoriaDeleteAPIView,
    CategoriaDetailAPIView,
    CategoriaListAPIView,
    CategoriaUpdateAPIView,
    # GROUP
    GroupDetailAPIView,
    GroupListAPIView,
    # LOCAL
    LocalCreateAPIView,
    LocalDeleteAPIView,
    LocalDetailAPIView,
    LocalListAPIView,
    LocalUpdateAPIView,
    # OCORRENCIA
    OcorrenciaCreateAPIView,
    OcorrenciaDelete,
    OcorrenciaDetail,
    OcorrenciaEdit,
    OcorrenciaList,
    # USER
    UserDetailAPIView,
    UserListAPIView,
    # USUARIO
    UsuarioCreate,
    UsuarioDelete,
    UsuarioDetail,
    UsuarioEdit,
    UsuarioList
)

# AS URLS A SEGUIR SEGUEM DA EXTENSÃO API/
urlpatterns = [

    # USER
    # Acesso a lista de usuários nativos do Django e seus detalhes
    url(r'^user$',
        UserListAPIView.as_view(), name="User List"),
    url(r'^user/(?P<pk>\d+)/$',
        UserDetailAPIView.as_view(), name="User Detail"),

    # GROUP
    # Acesso a lista de grupos de users nativos do Django e seus detalhes
    url(r'^group$',
        GroupListAPIView.as_view(), name="Group List"),
    url(r'^group/(?P<pk>\d+)/$',
        GroupDetailAPIView.as_view(), name="Group Detail"),

    # USUÁRIO
    # Acesso  a lista de usuários e seus detalhes
    url(r'^usuario$',
        UsuarioList.as_view(), name="Usuario List"),

    url(r'^usuario/create/$',
        UsuarioCreate.as_view(), name="Create Usuario"),

    url(r'^usuario/(?P<login>.*)/$',
        UsuarioDetail.as_view(), name="UsuarioDetail"),

    url(r'^usuario/(?P<pk>\d+)/edit/$',
        UsuarioEdit.as_view(), name="Usuario Update"),
    url(r'^usuario/(?P<pk>\d+)/delete/$',
        UsuarioDelete.as_view(), name="Usuario Delete"),

    # OCORRÊNCIA
    # Acesso a lista de ocorrências e seus detalhes
    # Bem como as funções create, retrieve, edit e delete
    url(r'^ocorrencia$',
        OcorrenciaList.as_view(), name="Ocorrencia List"),
    url(r'^ocorrencia/create/$',
        OcorrenciaCreateAPIView.as_view(), name="Create Ocorrencia"),
    url(r'^ocorrencia/(?P<pk>\d+)/$',
        OcorrenciaDetail.as_view(), name="Ocorrencia Detail"),
    url(r'^ocorrencia/(?P<pk>\d+)/edit/$',
        OcorrenciaEdit.as_view(), name="Ocorrencia Update"),
    url(r'^ocorrencia/(?P<pk>\d+)/delete/$',
        OcorrenciaDelete.as_view(), name="Ocorrencia Delete"),


    # CATEGORIA
    # Acesso a lista de categorias das categorias e seus detalhes
    # Bem como as funções create, retrieve, edit e delete
    url(r'^categoria$',
        CategoriaListAPIView.as_view(), name="Categoria List"),
    url(r'^categoria/create/$',
        CategoriaCreateAPIView.as_view(),
        name="Create Categoria"),
    url(r'^categoria/(?P<pk>\d+)/$',
        CategoriaDetailAPIView.as_view(), name="Categoria Detail"),
    url(r'^categoria/(?P<pk>\d+)/edit/$',
        CategoriaUpdateAPIView.as_view(), name="Categoria Update"),
    url(r'^categoria/(?P<pk>\d+)/delete/$',
        CategoriaDeleteAPIView.as_view(), name="Categoria Delete"),


    # LOCAL
    # Acesso a lista de  locais e seus detalhes
    # Bem como as funções create, retrieve, edit e delete
    url(r'^local$',
        LocalListAPIView.as_view(), name="Local List"),
    url(r'^local/create/$',
        LocalCreateAPIView.as_view(), name="Create Local"),
    url(r'^local/(?P<pk>\d+)/$',
        LocalDetailAPIView.as_view(), name="Local Detail"),
    url(r'^local/(?P<pk>\d+)/edit/$',
        LocalUpdateAPIView.as_view(), name="Local Update"),
    url(r'^local/(?P<pk>\d+)/delete/$',
        LocalDeleteAPIView.as_view(), name="Local Delete"),

]

unb_alerta/urls.py
# -*- coding: utf-8 -*-
"""unb_alerta URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/dev/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import TemplateView
from django.contrib.auth.models import User
from rest_framework_jwt.views import obtain_jwt_token
# import ocorrencia.urls
# import base.urls

urlpatterns = [
    url(r'^$', TemplateView.as_view(
        template_name='inicial.html'),
        name='inicio'),
    url(r'^admin/', admin.site.urls),
    url(r'', include('ocorrencia.urls')),
    url(r'', include('usuario.urls')),
    url(r'^captcha/', include('captcha.urls')),
    # url(r'', include(ocorrencia.urls)),
    url(r'^api/', include('api.urls')),
    url(r'^api-token-auth/', obtain_jwt_token),
    url(r'^api-auth/', include('rest_framework.urls',
                               namespace='rest_framework')),


    # # must come at the end
    # #   so that base /sistema/ url doesn't capture its children
    # url(r'', include(base.urls)),
]

admin.site.unregister(User)

base/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

ocorrencia/models.py
# -*- coding: utf-8 -*-
from django.db import models
from unb_alerta.utils import restringe_tipos_de_arquivo_img
from usuario.models import Usuario


class Categoria(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    tipo = models.CharField(max_length=45, blank=True, null=True)

    class Meta:
        verbose_name = 'Categoria'
        verbose_name_plural = 'Categorias'

    def __str__(self):
        return ('%(tipo)s') % {
            'tipo': self.tipo}


class StatusOcorrencia(models.Model):
    id = models.AutoField(db_column='ID', primary_key=True)
    status = models.CharField(max_length=45, blank=True, null=True)

    class Meta:
        verbose_name = 'Status'
        verbose_name_plural = 'Status'

    def __str__(self):
        return ('%(status)s') % {
            'status': self.status}


class Local(models.Model):
    id = models.AutoField(db_column='id', primary_key=True)
    nome_cod = models.CharField(
        max_length=40,
        verbose_name='Código')
    descricao = models.CharField(
        max_length=150,
        verbose_name='Local')
    pai = models.IntegerField(
        blank=True,
        null=True)
    longitude = models.FloatField()
    latitude = models.FloatField()

    class Meta:
        verbose_name = ('Local')
        verbose_name_plural = ('Locais')

    def __str__(self):
        return ('%(descricao)s') % {
            'descricao': self.descricao}


class Ocorrencia(models.Model):
    id = models.AutoField(primary_key=True)
    data = models.DateField(verbose_name='Data da Ocorrência')
    hora = models.TimeField(verbose_name='Hora da Ocorrência')
    descricao = models.TextField(
        blank=True,
        null=True,
        verbose_name='Descrição')
    descricao = models.TextField(
        blank=True,
        null=True,
        verbose_name='Descrição')
    informacoes_segurancas = models.TextField(
        blank=True,
        null=True,
        max_length=1000,
        verbose_name='Informações dos Seguranças')
    foto = models.ImageField(
        max_length=45,
        validators=[restringe_tipos_de_arquivo_img],
        blank=True,
        null=True,
        upload_to='ocorrencia/%Y/%m/%d')
    validade = models.BooleanField(verbose_name='É válida?')
    atendida = models.BooleanField(verbose_name='Foi atendida?')
    emergencia = models.BooleanField(verbose_name='Emergência?')
    vitimado = models.BooleanField(verbose_name='Possui vítimas?')
    repetida = models.BooleanField(verbose_name='É repetida?')
    resposta = models.TextField(max_length=1000, blank=True, null=True)
    usuario_ID = models.ForeignKey(Usuario,
                                   related_name='usuario_usuario',
                                   verbose_name='Usuário')
    vigilante_ID = models.ForeignKey(Usuario,
                                     related_name='usuario_vigilante',
                                     verbose_name='Vigilante')
    tb_categoria_ID = models.ForeignKey(
        Categoria,
        verbose_name='Categoria')
    longitude = models.FloatField()
    latitude = models.FloatField()
    localidade = models.ForeignKey(
        Local,
        verbose_name='Local')
    status = models.ForeignKey(
        StatusOcorrencia,
        verbose_name='Status da Ocorrência',
        blank=True,
        null=True)

    data_publicacao = models.DateTimeField(
        verbose_name='Data de Criação da Ocorrência',
        blank=True,
        null=True)

    class Meta:
        verbose_name = ('Ocorrência')
        verbose_name_plural = ('Ocorrências')

    def __str__(self):
        return ('%(data)s - %(id)s') % {
            'data': self.data, 'id': self.id}

base/views.py
from django.shortcuts import render

# Create your views here.

templates/base.html
{% load staticfiles %}

{% block header%}

<!DOCTYPE html>
<html>

  <head>
    <title>UnB Alerta</title>
    <meta http-equive ="Content-Type" content ="text/html, charset-utf-8">
    <link rel="icon" href="{% static 'images/índice.jpeg' %}" type="image/png" >
  <link rel="stylesheet" type="text/css" href="{% static 'bootswatch.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
  <link href='https://fonts.googleapis.com/css?family=Varela+Round' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="{% static 'js/jquery.mask.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/bootstrap-datepicker.min.js' %}" type="text/javascript"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    <script src="{% static 'js/mascaras.js' %}"></script>
  <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
  
  <script src="https://cdnjs.cloudflare.com/ajax/libs/numeric/1.2.6/numeric.min.js"></script>
</head>

<script type="text/javascript">

function hamb_open() {
    document.getElementById("mySidenav").style.display = "block";
}

function hamb_close() {
    document.getElementById("mySidenav").style.display = "none";
}

function hamb_drop() {
    var x = document.getElementById("hambDrop");
    if (x.className.indexOf("hamb-show") == -1) {
        x.className += " hamb-show";
        x.previousElementSibling.className += " hamb-cor";
    } else {
        x.className = x.className.replace(" hamb-show", "");
        x.previousElementSibling.className =
        x.previousElementSibling.className.replace(" hamb-cor", "");
    }
}

function hamb_drop2() {
    var x = document.getElementById("hambDrop2");
    if (x.className.indexOf("hamb-show") == -1) {
        x.className += " hamb-show";
        x.previousElementSibling.className += " hamb-cor";
    } else {
        x.className = x.className.replace(" hamb-show", "");
        x.previousElementSibling.className =
        x.previousElementSibling.className.replace(" hamb-cor", "");
    }
}

function hamb_drop3() {
    var x = document.getElementById("hambDrop3");
    if (x.className.indexOf("hamb-show") == -1) {
        x.className += " hamb-show";
        x.previousElementSibling.className += " hamb-cor";
    } else {
        x.className = x.className.replace(" hamb-show", "");
        x.previousElementSibling.className =
        x.previousElementSibling.className.replace(" hamb-cor", "");
    }
}

$(document).ready(function(){
  
  if (screen.width <= 1080) {
    $('#desktop').hide(-999);
    $('#mobile').fadeIn(-999);
  }
    
});

</script>

{%endblock%}

{%block body%}

  <body>

    <!-- VERSAO DESKTOP !-->

    <nav class="navbar navbar-default" id="desktop">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'inicio' %}">UnB Alerta</a>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
            <ul class="nav navbar-nav">
            {% if user.is_authenticated %}
              <li class="dropdown">
                <a href="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                Estatísticas <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="{% url 'estatisticas' %}">Mapa</a></li>
                  <li class="divider"></li>
                  {% if perms.ocorrencia.change_ocorrencia %}
                    <li><a href="{% url 'gerar_relatorio' %}">Relatórios</a></li>
                    <li><a href="{% url 'gerar_grafico' %}">Gráficos</a></li>
                {% endif %}
                </ul>
              </li>

              {% if perms.ocorrencia.change_ocorrencia %}
                <li role="presentation" ><a href="{% url 'lista_validacao' %}">Validar Ocorrência</a></li>
                <li role="presentation" ><a href="{% url 'pesquisar_placas' %}">Procurar Placa</a></li>
              {% endif %}
              <li><a href="{% url 'criar_ocorrencia' %}">Fazer Ocorrência</a></li>
              <li class="dropdown">
                <a href="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Ocorrências <span class="caret"></span></a>
                <ul class="dropdown-menu" role="menu">
                {% if perms.ocorrencia.change_ocorrencia %}
                  <li><a href="{% url 'lista_ocorrencias' %}">Todas ocorrências</a></li>
                {% endif %}
                  <li class="divider"></li>
                  <li><a href="{% url 'minhas_ocorrencias' %}"> Minhas ocorrências</a></li>
                </ul>
              </li>
            </ul>
            <ul class="nav navbar-nav navbar-right" style="position:relative; right:5%;">

              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"             aria-expanded="false" style=" margin-right=50px;"> {{ user.username }} <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li><a href="{% url 'perfil' %}">Perfil</a></li>
                  <li role="separator" class="divider"></li>
                  <li><a href="{% url 'logout' %}">Sair</a></li>
                </ul>
              </li>

            </ul>
          {% else %}
            <ul class="nav navbar-nav">
              <li><a href="{% url 'cadastrar_usuario' %}">Cadastre-se</a></li>
              <li><a href="{% url 'login' %}">Entrar</a></li>
            </ul>
          {% endif %}
            <ul class="nav navbar-nav navbar-right" style="position:relative; right:4%;">
              <li><a href="{% url 'sobre' %}"> Sobre</a></li>
            </ul>
        </div>
      </div>
    </nav>

    <!-- VERSAO MOBILE !-->

    <nav class="hamb-sidenav hamb-dark-grey hamb-animate-left" style="display:none" id="mySidenav">
      <a href="javascript:void(0)" onclick="hamb_close()"
      class="hamb-closenav hamb-large">Fechar &times;</a>
      
      {% if user.is_authenticated %}
        <div class="hamb-accordion">
          <a onclick="hamb_drop()" href="#"> Estatísticas <i class="fa fa-caret-down"></i></a>
          <div id="hambDrop" class="hamb-accordion-content hamb-white hamb-card-4">
            
            <a href="{% url 'estatisticas' %}">Mapa</a>
            {% if perms.ocorrencia.change_ocorrencia %}
              <a href="{% url 'gerar_relatorio' %}">Relatórios</a>
              <a href="{% url 'gerar_grafico' %}">Gráficos</a>
            {% endif %}

          </div>
        </div>

        {% if perms.ocorrencia.change_ocorrencia %}
          <a href="{% url 'lista_validacao' %}">Validar Ocorrência</a>
          <a href="{% url 'pesquisar_placas' %}">Procurar Placa</a>
        {% endif %}
        
        <a href="{% url 'criar_ocorrencia' %}">Fazer Ocorrência</a>

        <div class="hamb-accordion">
          <a onclick="hamb_drop2()" href="#"> Ocorrências <i class="fa fa-caret-down"></i></a>
          <div id="hambDrop2" class="hamb-accordion-content hamb-white hamb-card-4">
            
            {% if perms.ocorrencia.change_ocorrencia %}
              <a href="{% url 'lista_ocorrencias' %}">Todas ocorrências</a>
            {% endif %}
            <a href="{% url 'minhas_ocorrencias' %}">Minhas ocorrências</a>
            
          </div>
        </div>

        <a href="{% url 'sobre' %}">Sobre</a>


        <div class="hamb-accordion">
          <a onclick="hamb_drop3()" href="#"> {{ user.username }} <i class="fa fa-caret-down"></i></a>
          <div id="hambDrop3" class="hamb-accordion-content hamb-white hamb-card-4">

            <a href="{% url 'perfil' %}">Perfil</a>
            <a href="{% url 'logout' %}">Sair</a>

          </div>
        </div>

      {% else %}

        <a href="{% url 'cadastrar_usuario' %}">Cadastre-se</a>
        <a href="{% url 'login' %}">Entrar</a>
        <a href="{% url 'sobre' %}">Sobre</a>

      {% endif %}
      
    </nav>

    <nav class="navbar navbar-default" id="mobile">
      <div class="hamb-container">
        <input type="image" src="{% static 'images/hamb.png' %}" class="hamb-opennav hamb-xlarge" onClick="hamb_open()"/>
      </div>
      <a class="navbar-brand nav-right" href="{% url 'inicio' %}">UnB Alerta</a>
    </nav>

{% endblock %}

{% block content %}
{% endblock %}

{%block footer%}

    <footer class="footer-rodape">

      <div class="footer-esquerda">

        <h3>UnB<span>Alerta</span></h3>

        <p class="footer-links">
          <a href="{% url 'inicio' %}">Inicio</a>
          ·
          <a href="{% url 'sobre' %}">Sobre</a>
          ·
          <a href="#">Contato</a>
        </p>

        <p class="footer-unbalerta">Equipe Unb Alerta &copy; 2016</p>
      </div>

      <div class="footer-direita">

        <i class="fa fa-map-marker"></i>
        <p><span>Universidade de Brasilia</span> Brasilia, DF</p>
      
        <i class="fa fa-phone"></i>
        <p>(61) 3107-6222</p>
      
        <i class="fa fa-envelope"></i>
        <p><a href="mailto:unbalerta@gmail.com">unbalerta@gmail.com</a></p>
        
      </div>

    </footer>

{%endblock%}

  </body>
</html>

templates/inicial.html
{% extends "base.html"%}
{% load static from staticfiles %}
{% block content %}

<center>
<div class="inicial">
	<div class="block">
		<br><h1>Colabore com a <br>sua segurança.</br>
      Permita-nos te<br> ajudar.</h1>
		<h2> O projeto UnB Alerta tem como objetivo facilitar a comunicação entre</br>
		os estudantes da Universidade de Brasília e a viligância da Universidade.</h2>
	</div>
	<div class="block">
		<img height=450px src="{% static 'images/securityguard.jpg' %}">
	</div>
	<div class="block">
		<br><h1><center>Faça o download do aplicativo</center></h1>
		<h2><center><b>Para realizar o download</b> você deve acessar o site www.google.com.br e
		pesquisar pelo aplicativo na loja, blá blá blá, teste de tamanho do texto
		na página inicial. O texto aparentemente ficou em um tamanho aceitável para
		o tamanho da página.</center></h2>
	</div>
</div>
</center>

{% endblock %}

templates/login.html
{% extends "base.html"%}
{% block content %}
<div id = "fundo">
<div class="container">
    <div class="row vertical-offset-100">
      <div class="col-md-4 col-md-offset-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Please sign in</h3>
          </div>

          <div class="panel-body">
            <form accept-charset="UTF-8" role="form">
                    <fieldset>
            <div class="social-box">
              <div class="row mg-btm">
                <div class="col-md-12">
                <a href="#" class="btn btn-primary btn-block">
                  <i class="icon-facebook"></i>    Login with Facebook
                </a>
                </div>
              </div>
            </div>
                <div class="form-group">
                  <input class="form-control" placeholder="E-mail" name="email" type="text">
              </div>
              <div class="form-group">
                <input class="form-control" placeholder="Password" name="password" type="password" value="">
              </div>
              <div class="checkbox">
                  <label>
                    <input name="remember" type="checkbox" value="Remember Me"> Remember Me
                  </label>
                </div>
              <input class="btn btn-lg btn-success btn-block" type="submit" value="Login">
            </fieldset>
              </form>
          </div>
      </div>
    </div>
  </div>
</div>
<div>
{% endblock %}

templates/mapa.html
{% extends "base.html"%}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content %}

<link rel="stylesheet" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
<script src="/static/js/jquery.mask.min.js"></script>


<style type="text/css">
  #map {
    width: 90% !important;
    height:550px !important;
    margin-left:5% !important;
    margin-top:2% !important;
    overflow: visible !important;
    border : 3px solid rgba(211,211,211,0.4);
  }
</style>

<script src="{% static 'js/markerclusterer.js' %}"></script>

<script async defer
      src="https://maps.googleapis.com/maps/api/js?callback=initMap&libraries=geometry">
</script>

<script type="text/javascript">
  var map;
 // var pontos = {0:{lat:0.0, lng:0.0}};  
  var pontos = [];
  
  for (var i = 0; i < {{numero_res}}; i++) {
//    pontos[i].lat = ({{array_lat}}[i]);
  //  pontos[i].lng = ({{array_long}}[i]);
  pontos[i] = { lat: {{array_lat}}[i], lng: {{array_long}}[i]};
  };
  console.log({{numero_res}});
  /*
  console.log({{array_lat}})
  foreach(var elem in {{array_lat}}.length; i++) {
    ponto.lat = {{array_lat}}[i];
    ponto.lng = {{array_long}}[i];
    pontos.append(ponto);
  };
  console.log(pontos);*/
  function initMap() {
    
    map = new google.maps.Map(document.getElementById('map'), {
      center: {lat: -15.763606, lng: -47.869636},
      zoom: 17,
      mapTypeId: google.maps.MapTypeId.ROADMAP
    });
    
    var markers = [];
    for (i=0; i < {{numero_res}}; i++){
      var marker = new google.maps.Marker({
        position: pontos[i],
        map: map,
      });
      console.log(typeof(pontos[i]));
      console.log(typeof(marker.position));
      markers.push(marker);
    }
    
    var options = {
      imagePath: '../../static/images/m'
    };
    
    var markerCluster = new MarkerClusterer(map, markers, options);
}
</script>

<div id = "fundo">
  <div class="container">
    <div class="row vertical-offset-100">
      <div class="col-md-10 col-md-offset-1">
        
        <nav class="navfilter">
          <div class="container-fluid" >
            {% crispy filter.form %}
          </div>
        </nav>
        
        <div class="panel panel-primary">
          <div class="panel-heading" style="text-align:center">
            <h1>Mapa com estatisticas</h1>
          </div>

          <div class="panel-body">
            <div class="form-group">
            
              <b><div id="resultado" style="text-align:center; color:#4E6c24;"></div></b>
              <div id="map" ></div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>


{% endblock %}

templates/pagination.html
{% if is_paginated %}
  <nav class="text-center">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}{{filter_url}}">
            <span class="pager-prev">Anterior</span>
          </a>
        </li>
      {% else %}
        <li class="pager-prev disabled"><a href="">Anterior</a></li>
      {% endif %}

      {% for page in page_range %}
        {% if page == None or page == 'None' %}
          <li class="page-item disabled">
            <a class="page-link" href="">...</a>
          </li>
        {% else %}
          <li {% if page == page_obj.number %} class="page-item active" {% endif %}>
            <a class="page-link" href="?page={{ page }}{{filter_url}}">{{ page }}</a>
          </li>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}{{filter_url}}">
            <span class="pager-next">Próxima</span>
          </a>
        </li>
      {% else %}
        <li class="pager-next disabled"><a href="">Próxima</a></li>
      {% endif %}
    </ul>
  </nav>
{% endif %}

templates/sobre.html
{% extends "base.html"%}
{% block content %}
<div class = "sobre">
	<h4>O UnB Alerta é um projeto desenvolvido pelos alunos da disciplina Linguagens de Programação, Turma A, do semestre 1/2016. Orientados pelo professor Marcelo Ladeira, os alunos desenvolveram um sistema que tem como objetivo de contribuir com a segurança da Universidade de Brasília,
	facilitando a comunicação entre alunos e vigilntes.</h4></br>

	<h3 style="color:#247ba0"><b>Para a comunidade universitária:</b></h3></br>

	<h4>Registrar uma ocorrência no sistema é simples: Acesse a aba de "Cadastrar Ocorrência" no menu superior do site, selecione a localização do acontecimento no mapa e preencha os campos obrigatórios. Tente descrever o acontecimento com a maior quantidade de detalhes possível. Também é possível anexar fotos, além de ser possível cadastrar tanto ocorrências que exigem ação imediata quanto acontecimentos passados. Após enviar sua ocorrência, a equipe de segurança poderá entrar em contato com você e dar feedback sobre sua denúncia.</h4></br>

	<h4>A aba "Estatísticas no Mapa" mostra a localização das ocorrências dentro da UnB, e pode ajudar os usuários a evitar locais de maior risco. Também é possível visualizar as ocorrências validadas pela equipe de segurança, filtrá-las segundo parâmetros do seu interesse e listar suas ocorrências enviadas.</h4></br>

	<h3 style="color:#247ba0"><b>Para a equipe de segurança:</b></h3></br>

	<h4>Com o sistema UnB Alerta, é possível ver as ocorrências enviadas pelos usuários e respondê-las, além de gerar relatórios para acompanhar as estatísticas sobre os acontecimentos anormais na Universidade. Também é possível verificar dados dos donos de carro que registraram suas placas no sistema e buscar ocorrências por data, tipo ou local.</h4></br>


	<h4>
	Contribuir com o projeto irá ajudar a mapear acontecimentos anormais dentro da Universidade de Brasília e ajudar a equipe de segurança a garantir um ambiente acadêmico mais seguro para a comunidade universitária.</h4></br>
</div>

{% endblock %}